- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- name: 'Add Admin rights'
  hosts: masters[0]
  gather_facts: no
  tasks:
    - name: make OpenShift user cluster admin
      shell: "oc adm policy add-cluster-role-to-user cluster-admin {{ ocp_admin }} --config=/etc/origin/master/admin.kubeconfig"

- name: 'Set registry to use Azure Storage'
  hosts: masters[0]
  gather_facts: no
  tasks:
  - name: Configure docker-registry to use Azure Storage
    shell: oc set env dc docker-registry -e REGISTRY_STORAGE=azure -e REGISTRY_STORAGE_AZURE_ACCOUNTNAME={{ registry_storage_account_name }} -e REGISTRY_STORAGE_AZURE_ACCOUNTKEY={{ registry_storage_account_key }} -e REGISTRY_STORAGE_AZURE_CONTAINER=registry -e REGISTRY_STORAGE_AZURE_REALM=core.windows.net

- name: 'Configure Network policy'
  hosts: masters[0]
  gather_facts: no
  tasks:
    - name: Copy policies
      copy:
        src: "{{ inventory_dir }}/policies"
        dest: "/home/{{ ocp_admin }}/"
    - name: Get List of OpenShift Projects
      command: oc get namespaces --output=name
      register: openshift_namespaces
    - name: Apply Default Policies
      shell: |
        for pol in ~/policies/baseline/*.yml; do
          oc apply -f $pol -n {{ item | basename }}
        done
        if [ -d ~/policies/{{ item | basename }} ]; then
          for pol in ~/policies/{{ item | basename}}/*.yml; do
            oc apply -f $pol -n {{ item | basename }}
          done
        fi
      with_items: "{{ openshift_namespaces.stdout_lines }}"
