openshift_project_request_template_edits:
  - key: objects
    action: append
    value:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: default-deny
      spec:
        podSelector:
  - key: objects
    action: append
    value:
      apiVersion: network.openshift.io/v1
      kind: EgressNetworkPolicy
      metadata:
        name: deny-external-egress
      spec:
        egress:
        - type: Deny
          to:
            cidrSelector: 0.0.0.0/0
  - key: objects
    action: append
    value:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-from-same-namespace
      spec:
        podSelector:
        ingress:
        - from:
          - podSelector: {}
  - key: objects
    action: append
    value:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: allow-from-default-namespace
      spec:
        podSelector:
        ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                name: default
